language: java
jdk: openjdk11
branches:
  only:
  - develop
  - "/^release-[0-999].[0-999]/"
  - master
notifications:
  email:
    recipients:
    - brotherowsky@gmail.com
script:
- mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
- mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=lconder
  -Dsonar.projectKey=lconder_ecosystem-demo -Dsonar.login=$SONAR
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU
  on:
    branch: master
  app: ecosystem-demo-lconder
